use_frameworks!

target 'PromisedArchitectureKit_Example' do
  pod 'PromisedArchitectureKit', :path => '../'

  target 'PromisedArchitectureKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
